### ISSUE TITLE
Unable to install, does Linux Deploy support Android 10?

### ISSUE THREAD

**Issue by Uchiha-Peng** [meefik/linuxdeploy#1126]
My phone is Redmi Note7, already root
The system is the Android 10 Google Pixel experience
There is an error installing CentOS or Ubuntu. The contents of output.log are as follows, but I can't see the detailed cause of the error. I want to know if Linux Deploy supports Android 10, thank you.

>  deploy
:: Installing bootstrap/rootfs ... 
Checking installation path ... done
Making new disk image (4095 MB) ... done
Making file system (ext4) ... done
Checking file system ... done
Mounting the container: 
/ ... fail
<<< deploy

**Comment by bleeee** [comment]
same here

**Comment by ChristopheBW** [comment]
OnePlus7pro oos Android 10, what ever the file are, can't be mounted. But it was worked on Android 9

**Comment by Danct12** [comment]
This app needs an update to [system-as-root (a feature from on Android 10)](https://source.android.com/devices/bootloader/system-as-root)  and it should work again.

**Comment by drygdryg** [comment]
Faced the same problem

**Comment by spinsupreme** [comment]
OMG finally.. I didn't think to raise the issue here. I been having this problem since the 1+7pro beta#2 and reverted to 9.. then I was told they fixed it and the COD crashing in the stable O²OS10..it wasn't so and isn't as of yesterday when 1+ got me with an OTA somehow, but I used the MSM tool from when I converted from T-Mobile to go back to pie So since I don't listen to

**Comment by Danct12** [comment]
This should be closed now, as Linux Deploy 2.5.0 added support for Android 10. See CHANGELOG.md.
