### ISSUE TITLE
Configuring core/profile ...  Segmentation fault

### ISSUE THREAD

**Issue by DesktopECHO** [meefik/linuxdeploy#1300]
Good day,

I have a Pi-hole image in CentOS that successfully deploys to **every** ARMv7 Android ever attempted, except the Samsung Galaxy Tab.  Actually, two Tabs -- An SM-T813 and SM-T819.

Does anyone have an idea why Linux Deploy would throw a segfault deploying a CentOS 7 instance on these devices?  Or next steps for troubleshooting?
`````
>>> deploy
## bootstrap/rootfs : do_install && do_configure
:: Installing bootstrap/rootfs ... 
Checking installation path ... done
Making file system (ext4) ... done
Checking file system ... done
Mounting the container: 
/ ... done
/proc ... done
/sys ... done
/dev ... done
/dev/shm ... skip
/dev/pts ... done
Importing rootfs from tar.gz archive ... done
## core/emulator : do_install && do_configure
## core/motd : do_install && do_configure
:: Configuring core/motd ... 
## core/hosts : do_install && do_configure
:: Configuring core/hosts ... 
## core/hostname : do_install && do_configure
:: Configuring core/hostname ... 
## core/mnt : do_install && do_configure
:: Configuring core/mnt ... 
## core/net : do_install && do_configure
:: Configuring core/net ... 
## core/timezone : do_install && do_configure
:: Configuring core/timezone ... 
## core/su : do_install && do_configure
:: Configuring core/su ... 
## core/locale : do_install && do_configure
:: Configuring core/locale ... 
## core/aid : do_install && do_configure
:: Configuring core/aid ... 
## core/profile : do_install && do_configure
:: Configuring core/profile ... 
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
Segmentation fault
## core/sudo : do_install && do_configure
:: Configuring core/sudo ... 
## core/unchroot : do_install && do_configure
:: Configuring core/unchroot ... 
## core : do_install && do_configure
## bootstrap : do_install && do_configure
## init/run-parts : do_install && do_configure
## init : do_install && do_configure
<<< deploy
`````
Thank you!
D.

**Comment by Sinusflorian** [comment]
![Screenshot_20220131-200321_Pixel_Launcher](https://user-images.githubusercontent.com/93134772/151856325-5974b2e2-d5d5-46fd-8d1a-4204ceea4f67.png)
![Screenshot_20220131-200304_Einstellungen](https://user-images.githubusercontent.com/93134772/151856330-193cc4d1-9298-46f8-a4b9-5b924a9ef740.png)

@DesktopECHO thanks for make a New thread, as you wrote before to flash root i flashed already when i installed the lineage OS 16 together and the g apps too. The FUNNY thing is that in almost every forum people complain about g apps running in Lineage xD but i habe zero issues ^^  and i thanks all who will read this xD .... All in want was to run a pihole and now i weht as programming noob through a Odyssey 😂

**Comment by Sinusflorian** [comment]
@DesktopECHO have a other idea i had to adjust locations for install and source maybe the segmentation error is because it cant find a install location or so? Screenshots attaching...

![Screenshot_20220131-202109_Linux_Deploy](https://user-images.githubusercontent.com/93134772/151858921-72475330-efc5-4675-8b16-9245abf0c070.png)
![Screenshot_20220131-202022_Dateimanager_+](https://user-images.githubusercontent.com/93134772/151858926-7fd5deec-61f8-4a35-a87f-8146f3b34be5.png)

**Comment by DesktopECHO** [comment]
Try installing to a different location on the device's filesystem to see if you have any better luck.  You can also try using ext2 instead of ext4.

Also, Linux Deploy has options to deploy the instance as a disk image (default) or as a folder on the Android device's filesystem.  Maybe try deploying to filesystem instead of disk image?

You can also try installing LineageOS 15 or 17 to verify that the issue occurs across different ROMs.

**Comment by Sinusflorian** [comment]
Ok here i am again. Nope i didn't had succsess, here is what i tried:

• Different Location
• ext versions make no difference
• Install on foldermode made the OS Crash!
• OS 15 is not Booting, OS 17 halbbricked Tablet, 
   had to start TWRP with PC then i went back to 
   OS 16. The Update with the Updater to the 25. 
  Januarversion of 16.
• Tried other Busyboxes Version
• Tried older Versions of Linux Deploy
• Tried Magisk instead of OS 16 RootAddon

Now the day is over (7:40 PM) and i'm exhausted. I will put some pictures in + traced log + crashvideo.

I hope that SOMEBODY kann help me xD Thanks for reading and Thanks @DesktopECHO for helping me. ^^ i will put this on hold till someome or me can find a solution. ^^

[output.log](https://github.com/meefik/linuxdeploy/files/7981146/output.log)
![Screenshot_20220201-191841_Linux_Deploy](https://user-images.githubusercontent.com/93134772/152031204-d2427c7b-141e-4e46-8813-fd8a23166003.png)
![Screenshot_20220201-191829_Linux_Deploy](https://user-images.githubusercontent.com/93134772/152031207-7f61a7fa-c8b4-42ae-a089-70f48f4b756b.png)
![Screenshot_20220201-191531_Linux_Deploy](https://user-images.githubusercontent.com/93134772/152031211-2fd1909e-6737-46d7-8138-558c957df146.png)
![Screenshot_20220201-191515_Linux_Deploy](https://user-images.githubusercontent.com/93134772/152031212-63974ae1-9f84-461c-9bb8-ab4fa6d42727.png)
![Screenshot_20220201-191420_Linux_Deploy](https://user-images.githubusercontent.com/93134772/152031213-b34f6864-eb4f-48e1-ab78-655a1bfc7723.png)
![Screenshot_20220201-132517_Linux_Deploy](https://user-images.githubusercontent.com/93134772/152031217-a8e140c5-7e62-430e-ae83-ff666c84e655.png)
![Screenshot_20220201-132306_BusyBox](https://user-images.githubusercontent.com/93134772/152031219-d563ee0d-7c49-48fb-95bf-8fba6f4ec4e2.png)
![Screenshot_20220201-132243_Root_Checker_Basic](https://user-images.githubusercontent.com/93134772/152031222-a839d735-ec57-4dcf-8d18-8f2df228e28b.png)


https://user-images.githubusercontent.com/93134772/152032314-e7b3a35c-278c-4864-825b-8ce5a668067f.mp4

**Comment by DesktopECHO** [comment]
Hi, try enabling the Telnet daemon in Linux Deploy, then uncheck "localhost only" so you can reach it from your home PC.


`````
[zero@macpro ~]$ telnet 10.13.12.11 5023
Trying 10.13.12.11...
Connected to 10.13.12.11.
Escape character is '^]'.

Linux Deploy aarch64 /dev/pts/0
`````
Try this:
`````
/data/data/ru.meefik.linuxdeploy/files/bin/linuxdeploy mount
/data/data/ru.meefik.linuxdeploy/files/bin/linuxdeploy status
`````
Maybe that will give us some clues.

**Comment by DesktopECHO** [comment]
One more thing... Can you try deploying a CentOS 7 (or Ubuntu 18.04) instance using Linux Deploy's built-in functionality?  Make sure you select **aarch64** for the architecture.

**Comment by DesktopECHO** [comment]
Also please try this ROM if you're still not having luck.
https://forum.xda-developers.com/t/rom-unofficial-lineageos-14-1-t813-t713-delta-nougat.3935079/
I think you will have a better chance of success with this one.

**Comment by Sinusflorian** [comment]
Thanks for all these Info wow 😊 will try it in the next Days or so. Need a little Break, but then lets continue with fresh power xD 😊 i keep you informed. 👍

**Comment by Sinusflorian** [comment]
OK here i am... again^^ First i installed Lineage OS 14.1 what you mentioned, installed all Apps back, selinux switched to permissive, Busybox installed.... aaaaaand again same Segmentation Error.

Telnet idk i don't get it working XD 

Cent OS 7 aarch64 was installed BUT with errors and yes starting sayd error too!

I attach all logs and screenshots of my actions. I Think this is a very deep Samsung thing, that they protect the corefile so heavy on that Tabs that we need a Samsung Android Expert lol.

But Thanks again for the Tipps, and for Reading my complaints lol ^^
![IDK what i do PC](https://user-images.githubusercontent.com/93134772/152166711-9b48d865-9a25-4933-ade9-38c4aba05cc3.png)
![IDK wht i do Android](https://user-images.githubusercontent.com/93134772/152166717-9e132996-3005-490a-9124-80dda7e67fea.png)
[Log Cent OS 7.log](https://github.com/meefik/linuxdeploy/files/7986977/Log.Cent.OS.7.log)
[output Pihole.log](https://github.com/meefik/linuxdeploy/files/7986978/output.Pihole.log)
[output start Cent OS 7.log](https://github.com/meefik/linuxdeploy/files/7986979/output.start.Cent.OS.7.log)

Edit: yeah sry Verbindungsfehler is connections errors XD

**Comment by DesktopECHO** [comment]
> output start Cent OS 7.log
>> rc.local ... -bash: /etc/rc.local: Permission denied

For the 'clean' install you just performed (Nothing to do with the Pi-hole image) - This is a different, correctable issue!

Regarding your telnet issue; you need to go to Linux Deploy and Enable Telnet Server first (and uncheck localhost only)  Then from your PC, telnet to the Android device.

EDIT:  I don't use/need Termux I find working in a Bash shell from a phone pretty irritating!

**Comment by Sinusflorian** [comment]
New Day, new Chanche lol, Here is the requested Telnetlog attached and yes i know i had a little error in my brain XD surely i had to change IP adress to mine, sry when you got a telnetrequest instead often XD

Ok then i tried to work on the rc.local issue too with telnet on this, but its in the logs.

I cannot say enough to thank you for standing with this with me by with this stupid S2 Tablet XD 😅

Yeah i know, was just little confused how to telnet and readed your text wrong, then i thought, hey just try on both on tablet and on PC. (German speaking person with almost self learned english, schoolenglish was horrible here haha)

Edit: ohhh dear, the telnet log got squeezed in the gap of the 2 screenshots ^^

![Picture of same error on Tablet](https://user-images.githubusercontent.com/93134772/152305371-7a1648dc-241a-4dc0-aa59-1ed0970b7f91.jpg)
[Telnetlog.txt](https://github.com/meefik/linuxdeploy/files/7992841/Telnetlog.txt)
![Telnetpicture](https://user-images.githubusercontent.com/93134772/152305379-26326067-5a72-4d17-aca7-e6bfa6a3a232.jpg)

**Comment by DesktopECHO** [comment]
I'm going to close this issue and we'll go back to the Pi-hole for Windows issues page on GitHub.  This doesn't seem like a Linux Deploy issue, more so it's your stubborn Galaxy Tab.  See [here](https://github.com/DesktopECHO/Pi-hole-for-Android/issues/6) for further correspondence.
