### ISSUE TITLE
Enhancement: support CASTING

### ISSUE THREAD

**Issue by lbdroid** [meefik/linuxdeploy#232]
In graphic subsystem, it supports VNC, Xserver, and framebuffer. It would be very useful to add a cast option (i.e. for chromecast and google TV devices).

Consider use-case: presentations using libreoffice + impress remote. The chromecast device can be configured to android tablet/phone's "portable hotspot", running full libreoffice impress. Presentation loaded through impress remote on Android, controlling the impress output via the chromecast on a projector.

**Comment by ShapeShifter499** [comment]
@lbdroid I tried casting with a level of success using Chromium. Turns out the Cast Extension for Chrome also works in Chromium even on ARM devices. There were a few issues though, no audio when casting the entire desktop, screen coloring was off (only red as far I could tell, showed up as yellow), and it was slower than expected. If the color had rendered correctly on the chromecast side the speed would have been ok for some presentations like power point in OpenLibre

**Comment by lbdroid** [comment]
That is an interesting, if somewhat roundabout approach. Casting the Android screen wouldn't work for this application at all though, since a presentation depends on the Android-side control application (Impress Remote).

Ideally, the casting function really should be native to the application. The performance issues you found are a result of several different layers of conversion. Best to get chrome out of the picture, set up a framebuffer that matches the target display resolution (probably one of 1920x1080, 1280x720, 1024x768) and dump it straight out to cast.

**Comment by lpreams** [comment]
+1 this would be an interesting feature to have. Does the Cast API actually support direct framebuffer manipulation? If it really is a simple as dumping the framebuffer to the Cast API, and framebuffer is already implemented in Linux Deploy, this might as well be a feature.

**Comment by twaik** [comment]
Cast API should be supported by Xorg/Xvnc. LD has no internal output support, so Cast API can not be used in LD.
