### ISSUE TITLE
FTDI USB

### ISSUE THREAD

**Issue by m4son** [meefik/linuxdeploy#281]
please add support for ftdi usb dongles, they are found but not attached to /dev/ttyUSBx

**Comment by meefik** [comment]
Driver support implemented in the kernel. Linux Deploy does not affect the kernel and modules.

**Comment by m4son** [comment]
Well, it doesnt work on my A20 AndroidTV box. I will add some more info later.

**Comment by kdb424** [comment]
You would need to add support in your kernel, compile it, then flash that, which is not the easiest task. Either way, that's unfortunately not a problem of this application. Anddroid would need to support the device for it to get passed to the Linux Chroot, as all the chroot can see is what's passed to it.

**Comment by ldeploynoob** [comment]
I'm dealing with this issue, too, running Debian jessie on my Acer B1-750 tablet.

The FTDI cable is found but not attached when checking lsusb.  I get the same result as m4son, with a Bus# and Device# listed for the cable, but I do not get the expected message like "FTDI USB Serial Device converter now attached to ttyUSB0"

I'm trying to run RomRaider logger with this cable, and that app starts up with a com port selected as /dev/ttyS0 with Linux Deploy.  But I can't figure out a way to map the the FTDI cable to be ttyS0.  The FTDI cable does not show up as a separate entry under /dev/ in Linux Deploy.  It's nowhere in the tty list.

I was confused at first by the replies here, and I initially thought there were separate Android kernels and Linux kernels at play, but if I understand it correctly now, there's only 1 (Android) kernel involved.  On this device, "About tablet", it shows up as a pretty old version, "3.10.20+."

So because kdb424 commented about adding FTDI support to the kernel, I initially tried to do that inside my Linux Deploy session.

But there is no /lib/modules/ directory within the Linux Deploy session.  So although I wanted to try "modprobe usbserial" and "modprobe ftdi_sio", I get the response:

modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/3.10.20+/modules.dep.bin'

So there is no such directory and no such file.

So I guess meefik's point is that ONLY the Android kernel is capable of being modified, and that is beyond the scope of Linux Deploy.

Dmesg reports the following on my device, both under an Android terminal and also in Linux, so if anyone has an idea to get around this problem, I'd like to hear about it:

[ 9004.133760] usb 1-1: new full-speed USB device number 3 using xhci_hcd
[ 9004.159851] usb 1-1: New USB device found, idVendor=0403, idProduct=6001
[ 9004.159890] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 9004.159915] usb 1-1: Product: FT232R USB UART
[ 9004.159935] usb 1-1: Manufacturer: FTDI
[ 9004.159954] usb 1-1: SerialNumber: A601XXXL
[ 9004.168747] gpio-keys gpio-lesskey.1.auto: Failed to request GPIO 222, error -517
[ 9004.168808] platform gpio-lesskey.1.auto: Driver gpio-keys requests probe deferral
[ 9004.168934] gpio-keys gpio-lesskey.2.auto: Failed to request GPIO 295, error -517
[ 9004.168977] platform gpio-lesskey.2.auto: Driver gpio-keys requests probe deferral

**Comment by twaik** [comment]
Not even a LD issue. Contact your vendor to get Android kernel working with your device.
