### ISSUE TITLE
i386 on ARM: debootstrap not found

### ISSUE THREAD

**Issue by iceblade112** [meefik/linuxdeploy#314]
I am using an ARM(32) device. After selecting "i386" architecture and starting the install, it fails after extraction.

Error:

    chroot: can't execute '/debootstrap/debootstrap': No such file or directory

Is there more to i386 emulation on ARM?

**Comment by CrazyJ36** [comment]
Choosing i386 simply would not work. This is why:
The debootstrap which starts the install doesn't understand your phone because you chose the wrong architecure.
Just like on PCs', you must install the linux image for your CPU architecture (ARM)
I don't think the app emulates linux either, just runs directly on the already "linux" Android through chroot, which is the method of getting Linux to run on Android.
I386 is just like an older Computer processor. Though Intel made A mobile processor for some Androids' with I386 architecture.
So make sure you choose "armhf" or "armel" as Architecure in the app.

**Comment by iceblade112** [comment]
In README.md:

"Supported architectures: ARM, ARM64, x86, x86_64, emulation mode (ARM ~ x86)"

**Comment by meefik** [comment]
For emulation mode needs support in the kernel binfmt_misc.

**Comment by iceblade112** [comment]
@meefik I tried with stock Dorimanx kernel (which has support, according to the kernel source) and I am currently running CyanogenMod.

**Comment by meefik** [comment]
See #315

**Comment by meefik** [comment]
For check binfmt_misc support: "Menu - Status".

**Comment by iceblade112** [comment]
Oh, okay. Thanks. I might try to compile binfmt_misc into the kernel.
