### ISSUE TITLE
Root default password doesn't work - linux deploy

### ISSUE THREAD

**Issue by h69pc** [meefik/linuxdeploy#412]
I installed kali in my s6 with linux deploy but cant login as root .... If i set a user in linux deploy i can login with that user but it doesnt have root permission , this user doesnt even have permissions to execute sudo ....... , the default root pass toor doesnt work either.... I tried also choose the user in linux deploy as root but no luck..... , anyone had this problem before....?, is there another other default root password besides toor , thanks for your help :-).
 maybe it has something to do with the /etc/init.d/myscript giving an error. ... anyone has suggestions for passwords to log in as root?

**Comment by JeffreyRFox** [comment]
On my Ubuntu install (with the Terminal Emulator app installed) selecting 'terminal' starts the Terminal Emulator app with a script designed to give you root access. Try it.

**Comment by h69pc** [comment]
Ei jeffreyRfox i tried before but it crashes everytime i try to start it , the only way i can login is through ssh , i will try to read the logs to see if i can find something

**Comment by expphoto** [comment]
On Ubuntu I can't use root either. SU asks for password, but it's not the default. Sudo gives a setuid error. Did you guys find anything about it?

**Comment by DotERM** [comment]
Guys!, read my issue #349 , you need to install another ROM with Android 4.2.2, 4.3 doesn't allow Sudo by some reason, flashed CyanogenMod and it worked!

**Comment by develperbayman** [comment]
running androidx86 r-1 cannot login as root user either "toor"does not work......seems some peeps here are confused the user:"android" and the password "changeme" is to connect to the containter/gui through vnc and ssh however there is no mention about INSIDE the container to access  superuser.....my android is rooted so i cannot except that i need to install cyanogenmod.......what is the root password user:Android 
password:__________??

its NOT "toor" or "toorroot"or "meefik" or"root" or "password" or the password i set over "changeme"
and i cannot change the password without the root password 

other than not being able to access root(wich means i cant seem to install anything that isnt "apt-get" this is a pretty freaking cool app!!!!! runs great and i cannot thank you enough.....with i can use android as my primary and run a full linux distro on top wich means java!!!!!!! 👍 ......in my humble opinion this project is very important to the androidx86 community because it allows the gaps between android and pc to be filled

but to be frank on android x86 netflix does not work EXCEPT inside of linux deploy so i very much am counting on this....some reason on a ubuntu install i didnt need root......but i DO prefer debian

also i tried to install alsa-common (pretty much all alsa packages and pulse audio)....how do i get the sound to work??

android x86 r-1
debian
jessie
mate desktop 
install type:directory
using xserver+xsdl

last update was VERY badass
thanks again!!!!

**Comment by tshcherban** [comment]
Updated app to v2.0, cant use root on debian distro. What is default password?

**Comment by erm3nda** [comment]
Well... if you chrooted your image, you have "per design" an actually open root shell on your "yet on android terminal". So, go to your phone, then just `passwd` or `passwd user` and no more. Now you have the user/root password you like without deal with previous one.

**Comment by kaiof** [comment]
1. Mount the container in Linux Deploy.
2. Connect as android. Use this or your own values:
$ openssl passwd -1 -salt SaltSalt SecretPassword
3. Copy the output to your clipboard and go back to Android.
4. Open a terminal emulator.
5. Create a folder (e.g., "fix") in sdcard
$ mount /dev/loop0 /sdcard/fix
$ cd /sdcard/fix
6. Edit etc/shadow and paste the generated password in place of the * in the 'root' line. Do NOT change anything else.
7. Edit etc/ssh/sshd_config and add the line: PermitRootLogin yes
8. $ cd /sdcard
9. $ umount fix
10. Stop and restart the Linux Deploy container
11. Login as root, change the password, put things back, etc.

**Comment by Gn4S1** [comment]
It works for me with:
sudo su

**Comment by Anan5a** [comment]
type 
```bash
$ sudo passwd root
```
To set a root password after 1st installation. (Debian)

**Comment by cmdwhoami** [comment]
Thank you Anan5a...

Now if I could only get SoftEther to auto-start with init.d script.

**Comment by erm3nda** [comment]
@cmdwhoami just do `sudo su`, there's no password. UNIX root user is indeed the user you'll have when SSH in. You can enable init scripts also. I am not sure if you even gave a try to @Anan5a reply. It is working, both Ubuntu and Debian images as well.

Linux Deploy ROCKS.

**Comment by cryptocompress** [comment]
default user: `android`
default pass: `some random string` (can be set by clicking "settings" button; where you select distro)
With `sudo -s` you can became `root` when sshed into box.

**Comment by Aeres-u99** [comment]
In my case even `sudo -i` is working well and proper for becoming root.
