### ISSUE TITLE
File Permission

### ISSUE THREAD

**Issue by makerdark98** [meefik/linuxdeploy#430]
how to execute file in sdcard

if ls -l, -rw-rw----, 1 root aid_sdcard_rw 5512 Feb 21 01:27 a.out

I tried to change permission, but impossible..!

I don't know why I can't change permission in root

Please suggest a solution.

(I tried in home, can execute a.out)

**Comment by cloud9350** [comment]
Try this
chown root:root <filename>

**Comment by niggo372** [comment]
I think it's because Android mounts the sdcard as fat32 and with noexec, so there isn't really a concept of ownership and permissions, and even if there were one you could never get the x permission because of the mount option. The only workaround I found was to exec everything as root, since root can do whatever he/she wants.
