### ISSUE TITLE
Arch linux can't complete install - missing library required by pacman

### ISSUE THREAD

**Issue by zekeb** [meefik/linuxdeploy#529]
Had Arch installed on my LG G3 before.  Decided to create a fresh install.  The pacstrap command downloads all the base files, but when pacman begins the installation process, it fails with this error:
`/usr/bin/pacman: error while loading shared libraries: liblz4.so.1: cannot open shared object file: No such file or directory'
I have tried several different mirrrors.  Liblz4.so.1 does not appear to be present anywhere on my device, and is not present in the chroot environment either.
Hoping this can be resolved.  Linux deploy is non functional for Arch on armv7 presently.

**Comment by ruleh** [comment]
The same problem exists on x86.
I found a slightly long way out of this by manually extracting liblz4, reinstalling pacman from a local package and then reinstalling it again from the repository.

**Comment by zekeb** [comment]
Thanks for the response.   To be clear, you downloaded libz4 archive and extracted the so.1 file, then manually put it in /usr/lib in the chroot.  Then downloaded pacman archive and reinstalled it with what command? pacman -U? Will the original pacman package work once the lib is in place?  If so, why reinstall?

**Comment by ruleh** [comment]
Yes I downloaded the libz4 archive from here https://www.archlinux.org/packages/core/i686/lz4/
and moved it to the root directory of my install where I extracted it using android tools (because I had none in the chroot).
The archive is well structured so everything was extracted to where it needs to be.
This made pacman work but it was still very broken, especially the config files were a complete mess.
Installing pacman using "pacman -U --force <pacman package>" fixed the configs. The pacman archive was already under /var/cache/pacman/pkg .
Since the configs were fixed, downloading worked again.
I redownloaded pacman again from the repository using "pacman -S --force pacman" to reinstall all the dependencies (such as libz4) as packages since they weren't in the database.

I had to reinstall some other things that were also available on the system but not recognised as packages in pacman.

**Comment by fmsouza** [comment]
I tried to do what @ruleh mentioned, but it is not that 'simple' in ARM devices because there is no official support for arm lz4 package. Now I'm waiting for some kind of solution.

**Comment by fmsouza** [comment]
I actually managed to make it work with some handwork.

1. Downloaded official Archlinux latest build in http://ca.us.mirror.archlinuxarm.org/os/
2. Extracted to some place in my computer
3. Copied `/lib/liblz4.so.1` to `/sdcard/Download` in my device
4. Installed archlinux in the device normally until the error occurs
5. Open a Terminal app and run Linux Deploy by myself as root from the command configured in the `Settings` menu: `su -c "/data/data/ru.meefik.linuxdeploy/files/bin/linuxdeploy shell -u root"`. It starts the chroot as root
6. `cp /sdcard/Download/liblz4.so.1 /lib`
7. `pacman -Syu` is working

**Comment by fmsouza** [comment]
When I tried to `Reconfigure` the image with different configurations, such as different desktop environment, SSH, VCN, etc., I received a bunch of errors saying many things already exists.

The solution for this problem was enable `Debug mode` in `Settings`, to see every command it runs, and increase the max number of lines of commands to show (I enhanced from 100 to 1000, maybe there was no need for this amount). The I re-runned the `Reconfigure` option.

1. When the process stop with the erro, go up and copy the `pacman -Syq --noconfirm <packages>` command
2. Open a Terminal app and run Linux Deploy by yourself as root from the command configured in the Settings menu: `su -c "/data/data/ru.meefik.linuxdeploy/files/bin/linuxdeploy shell -u root"`
3. Run the copied command with the flag `--force`: `pacman -Syq --force --noconfirm <packages>`
4. Everything should be installed.

**Comment by Graywolfe813** [comment]
Easier fix:
Download and copy this to /data/data/ru.meefik.linuxdeploy/files/share

[https://www.dropbox.com/s/9ewzy23pjzyst64/cli.sh?dl=0](url)

It's cli.sh updated to include lz4 in base packages.

**Comment by sickhype** [comment]
No longer works

**Comment by Graywolfe813** [comment]
Edited comment above with CLI instructions

**Comment by ducklin5** [comment]
am i supposed to run cli.sh

**Comment by dcommisso** [comment]
I've found the same problem and I've easily fixed it adding "lz4" to the packages list in cli.sh. I made a pull request.

**Comment by meefik** [comment]
Fixed in version 1.5.6-194.
Download from: https://github.com/meefik/linuxdeploy/releases/tag/1.5.6

**Comment by DJKrip** [comment]
I have this bug on 1.5.6. ROM: CM13, ARCH: aarch64 INSTALLING TYPE:image

**Comment by iacchus** [comment]
Based on fmsouza's answer, you can

1. open an adb shell (which is equivalent to using an Terminal app),
2. go to the chroot dir, (default: `/data/local/linux`)
3. gain superuser (type command: `su`)
4. download the lib: (type the command: `wget http://mi.us.mirror.archlinuxarm.org/armv7h/core/lz4-131-2-armv7h.pkg.tar.xz` or any other mirror address)
5. unzip the lib in the very own chroot dir, as this way it will expand to correct directories (type command `tar xf lz4-131-2-armv7h.pkg.tar.xz`)
6. enter chroot (command: `su -c "/data/data/ru.meefik.linuxdeploy/files/bin/linuxdeploy shell -u root"`)
7. then try: `pacman -Syu`

**Comment by meefik** [comment]
Version 1.x is no longer supported. Please try version 2.0:
https://github.com/meefik/linuxdeploy/releases/tag/2.0.0

**Comment by Musickiller** [comment]
> Version 1.x is no longer supported. Please try version 2.0

does not work at all! (at least on my sm-t531)

**Comment by meefik** [comment]
Install [BusyBox](https://github.com/meefik/busybox/releases) in /system/xbin. Try to change "Settings -> PATH variable" to /system/xbin and run "Settings - > Update ENV".
