### ISSUE TITLE
Problem on installing Kali Linux on Android

### ISSUE THREAD

**Issue by TheDudeGuy0210** [meefik/linuxdeploy#777]
I downloaded Linux Deploy on my Android device and tried installing Kali Linux. I followed a tutorial that I found from YouTube so I copied everything he/she did, everything works fine but when I try connecting it to VNC Viewer, it says "VNC connection failed". After that I commented on his/her tutorial video and got replied. He/she asked me to try reinstalling Linux Deploy so I did it. Then, I tried installing Kali Linux again and this text appeared 

[20:10:47] >>> deploy
[20:10:47] :: Installing bootstrap/rootfs ... 
[20:10:47] Checking installation path ... done
[20:10:47] Making new disk image (2047 MB) ... done
[20:10:47] Making file system ... fail
[20:10:47] <<< deploy

I keep doing the same exact thing again for more than 10 times but the same text appeared. Any of you knows how to fix this, please help. I don't know anything about Linux Deploy or Kali Linux, I want to learn on using it. For those who would help, thank you.

**Comment by Somebodyhura** [comment]
The best way to install Linux is to set a separate partition for it.

I also encountered many problems whit installing as file.

So try this:

1_Insert you ram (atleast 16GB preferred class 10)

2_Install (Aparted) app for Android

3_Follow instructions and set atleast 8GB as ext4 for Linux installation and remain other for your own use 
(something like this: https://ibb.co/hSHYmQ)

4_then go into the Linux deploy, swipe right and go into settings

5_enable (lock screen), (wake lock), (CLI), (TELNET), (Localhost)

6_tap REMOVE ENV and UPDATE ENV

7_head back and click on download icon and set options like this:

Contain method: chroot (proot didn't work for me)
Distribution: Kali Linux
Architecture: Armhf
Distribution suite: Kali-rolling (It's better and newer)
Installation type: partition
Installation Path: mmcblk1p2 
(if you set like me it's ok...if not and set ext4 in first row at Aparted app then replace p2 with p1, they mean partition number)
File system: ext4
Username: Android
User Password: (needed for vnc only)
Privileged user:  root
DNS: Automatic
Localization: POSIX
INIT: (if you know how to work with, enable it...otherwise it's not needed, leave disabled)
MOUNTS: (Just like INIT)
SSH: enable (leave settings unaffected)
GUI: enable
Graphics subsystem: VNC (It's better than others)
GUI settings > Depth: 24Bit 
> DPI: 75
> width: 1600 height: 900 
(I set them at this numbers because nowdays 16:9 is a good aspect ratio and native with many monitors and also you won't encounter problems with programs that are a bit large, so I recommend changing it from the default value, that resolution is not compatible for some apps they go out of border :/ ) 
VNC Options: (leave unaffected)
Desktop environment: LXDE (what you desire, but that's my recommendation)

8_now head back and click the three dot menu and tap on install and wait until installation finishes

9_now connect with 127.0.0.1 with your password in vnc viewer app (recommend com.realvnc.viewer.android)

Hope this helps
Good luck and farewell---

**Comment by Somebodyhura** [comment]
One more thing:
If you are new to Linux I recommend Dual booting a full Linux beside a Windows on a PC so you can fully interact with the modern Linux and get used to it.
This Linux is not complete, have bugs and mainly it's used as a backup mobile Linux system for emergency situation, not for playing or having fun with it, but it's still not a bad start.
Remember this is minimal Linux...
Try Ubuntu or any other popular Linux on a desktop system to see it's full potential and features.

**Comment by TheDudeGuy0210** [comment]
I did everything you said but then, it showed this

>>> deploy
:: Installing bootstrap/rootfs ... 
Checking installation path ... fail
<<< deploy

What should do now? Thanks for the help.

**Comment by TheDudeGuy0210** [comment]
The partition corrupts my SD Card :/ I had to format it.

**Comment by Somebodyhura** [comment]
When you set partitions at (Aparted) app make the first one a (fat32) and second one a (ext4) then before applying go to phone settings and unmount SD card then head back to the app and start the formatting process.

When it is done ignore the corrupt SD card warning and eject your SD card then insert it again. 

When you insert your SD card again it should be known as a normal SD card and not corrupt, if this happens then the formatting went well and you should set your Android to use the SD card as a "portable storage" so it won't reformat it.

Now continue as the guide and it should be fine.

**Comment by Somebodyhura** [comment]
Hey mate...found the problem... There was a mistake in my guide, I already fixed it at wiki in (Installing Kali Linux Guide)  section.

It's about installation path...it's not "mmcblk1p2"
It's this:
"/dev/block/mmcblk1p2"

I forgot the "/dev/block/" part, try again and it should be OK now

**Comment by Somebodyhura** [comment]
I have also added some screenshots in the wiki.
Recommend you check it out.

**Comment by TheDudeGuy0210** [comment]
It finally worked, thanks for helping me! :)

**Comment by Somebodyhura** [comment]
Your welcome.

Please close the thread then ;)

**Comment by Killerp2542C** [comment]
My problem is when I run kali on nethunter kex it is perfectly fine.But after few minutes or rather I say after few seconds The screen went black and I have to Restart my Termux app and start kali and I happens every single time.
I can't figure it out and I can't find any tutorial for this problem.Help me!
