### ISSUE TITLE
I feel like something's missing with my Kali Linux, if there is can someone help me? 

### ISSUE THREAD

**Issue by TheDudeGuy0210** [meefik/linuxdeploy#778]
I recently just installed Kali Linux to my Android device then started learning to pentest wifi by aircrack-ng. When I typed "iwconfig" command it says that "no wireless extensions", then I tried typing "airmon-ng" but it didn't show any drivers, it only show "??????" and it shows "Not pci, usb, or sdio" to Chipset. It also shows "No session for pid *****"  everytime when I opened Kali. I'm a newbie, if there somethings wrong please explain about it to me :)                     
 - sorry for bad english

**Comment by Somebodyhura** [comment]
You can find the WiFi if you turn it on, but that's not the problem.
It's nothing wrong with the Linux deploy...the problem is:

Our mobile devices WiFi can't go on "airplane" mode for aircrack-ng to work.
They have the potential but the manufacturs are too lazy to put codes for supporting "airplane" mode in their WiFi driver. 
That's why there is no "airplane" mode in the WiFi driver and it can't go into that mode and Aircrack-ng or airmon or fern or reaver or whatever depends on WiFi "airplane" mode...won't work.

So just forget about WiFi pen testing on Android.

But.... I heard that some devices like "nexus" devices can support it.

Look for Kali Linux "net hunter" project.

**Comment by TheDudeGuy0210** [comment]
I get it now, thanks. I will look up for it.
