### ISSUE TITLE
can i use the whole space of internal sdcard to install linux application

### ISSUE THREAD

**Issue by zhanghuasong831** [meefik/linuxdeploy#989]
when i select the  Installation type to directory,the linux application data will default be stored in android phone's /data directory,but it is too small to my device,but my device have large space for /sdcard,so  can i make the linux application data be store in /sdcard.

sorry for my poor english

**Comment by KaMyKaSii** [comment]
I believe you can change the installation type to img and the img location to /sdcard/linux.img

**Comment by KaMyKaSii** [comment]
@zhanghuasong831 In this case the only solution would be to use the "directory" installation type, but it is not possible on /sdcard because it does not hold the permissions of the files. But I think you can create an image with a certain size and then increase if you think it is not enough
https://unix.stackexchange.com/questions/36123/how-to-resize-ext3-image-files

**Comment by zhanghuasong831** [comment]
@KaMyKaSii but the default directory when i select the installation to 'directory', it can be installed success,why? it has fix the permission problem, can i use the chmod or chwon command to fix it ?

**Comment by meefik** [comment]
See @875

**Comment by zhanghuasong831** [comment]
@meefik  OK thank you so much
